package com.hackathon.service;

import com.hackathon.dto.UserSelectionRequest;
import com.hackathon.model.ProblemStatement;
import com.hackathon.model.UserSelection;
import com.hackathon.repository.ProblemStatementRepository;
import com.hackathon.repository.UserSelectionRepository;
import lombok.RequiredArgsConstructor;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.PDPageContentStream.AppendMode;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

@Service
@RequiredArgsConstructor
@Transactional
public class UserSelectionService {
    
    private final UserSelectionRepository userSelectionRepository;
    private final ProblemStatementRepository problemStatementRepository;
    private final ProblemStatementService problemStatementService;
    
    /**
     * Register a user with a problem statement
     * Requirements:
     * 1. Email must be unique
     * 2. Email must end with @htcinc.com
     * 3. userId is auto-generated
     * 4. Max 2 users per problem statement
     */
    public UserSelection selectProblem(UserSelectionRequest request) {
        // Normalize email to lowercase for consistent validation and storage
        String normalizedEmail = request.getTeamLeadEmail().toLowerCase().trim();
        
        // Validate email format (case-insensitive)
        if (!normalizedEmail.endsWith("@htcinc.com")) {
            throw new RuntimeException("Email must end with @htcinc.com");
        }
        
        // Check if email already exists (unique user)
        Optional<UserSelection> existingUser = userSelectionRepository.findByTeamLeadEmail(normalizedEmail);
        if (existingUser.isPresent()) {
            throw new RuntimeException("This email is already registered. Each user must be unique.");
        }
        
        // Check if problem is available (max 2 users)
        if (!problemStatementService.canSelectProblem(request.getProblemStatementId())) {
            throw new RuntimeException("This problem statement has already been selected by 2 users. Please choose another.");
        }
        
        // Get problem statement
        ProblemStatement problemStatement = problemStatementService.getProblemStatementById(request.getProblemStatementId());
        
        // Create and save user selection
        UserSelection userSelection = new UserSelection();
        // userId will be auto-generated by @PrePersist in the entity
        userSelection.setTeamName(request.getTeamName());
        userSelection.setTeamLeadName(request.getTeamLeadName());
        userSelection.setTeamLeadEmail(normalizedEmail);
        userSelection.setProblemStatement(problemStatement);
        
        UserSelection savedSelection = userSelectionRepository.save(userSelection);
        
        // Update problem statement user count
        problemStatementService.updateUserCount(request.getProblemStatementId(), 1);
        
        return savedSelection;
    }
    
    public void deselectProblem(String email) {
        String normalizedEmail = email.toLowerCase().trim();
        Optional<UserSelection> selection = userSelectionRepository.findByTeamLeadEmail(normalizedEmail);
        
        if (selection.isPresent()) {
            Long problemStatementId = selection.get().getProblemStatement().getId();
            userSelectionRepository.delete(selection.get());
            problemStatementService.updateUserCount(problemStatementId, -1);
        }
    }
    
    public UserSelection getUserSelection(String email) {
        String normalizedEmail = email.toLowerCase().trim();
        return userSelectionRepository.findByTeamLeadEmail(normalizedEmail).orElse(null);
    }
    
    public List<UserSelection> getProblemSelectionUsers(Long problemStatementId) {
        return userSelectionRepository.findByProblemStatementId(problemStatementId);
    }

    public byte[] downloadSelectionReport(String email) throws Exception {
        String normalizedEmail = email.toLowerCase().trim();
        UserSelection selection = userSelectionRepository.findByTeamLeadEmail(normalizedEmail)
            .orElseThrow(() -> new RuntimeException("No selection found for this email"));

        try (PDDocument document = new PDDocument();
             ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {
            PdfWriter writer = new PdfWriter(document);
            writer.writeTitle("Vibeathon 2026 Selection Report");
            writer.writeSectionHeading("Participant Details");
            writer.writeField("User ID", selection.getUserId());
            writer.writeField("Team Name", selection.getTeamName());
            writer.writeField("Team Lead Name", selection.getTeamLeadName());
            writer.writeField("Team Lead Email", selection.getTeamLeadEmail());
            writer.writeField(
                "Selected Date",
                selection.getCreatedAt().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))
            );
            writer.writeSectionHeading("Selected Problem Statement");
            writer.writeField("Problem ID", selection.getProblemStatement().getProblemId());
            writer.writeField("Problem Title", selection.getProblemStatement().getTitle());
            writer.writeField("Problem Description", selection.getProblemStatement().getDescription());
            writer.close();
            document.save(outputStream);
            return outputStream.toByteArray();
        }
    }

    private static class PdfWriter {
        private static final float MARGIN = 50;
        private static final float TOP_MARGIN = 70;
        private static final float FONT_SIZE = 11;
        private static final float LABEL_WIDTH = 145;
        private static final float VALUE_GAP = 18;
        private static final float LINE_HEIGHT = 16;
        private static final float FIELD_GAP = 14;
        private static final float SECTION_GAP = 14;
        private static final float BOTTOM_MARGIN = 120;
        private static final float PAGE_WIDTH = PDRectangle.A4.getWidth();
        private static final float VALUE_WIDTH = PAGE_WIDTH - (2 * MARGIN) - LABEL_WIDTH - VALUE_GAP;
        private static final float TOP_IMAGE_MAX_WIDTH = PAGE_WIDTH - (2 * MARGIN);
        private static final float TOP_IMAGE_MAX_HEIGHT = 90;
        private static final float LOGO_MAX_WIDTH = 170;
        private static final float LOGO_MAX_HEIGHT = 55;
        private static final float LOGO_BOTTOM_Y = 28;

        private final PDDocument document;
        private final byte[] logoBytes;
        private final byte[] topImageBytes;
        private PDPage page;
        private PDPageContentStream contentStream;
        private float yPosition;
        private boolean isFirstPage = true;

        PdfWriter(PDDocument document) throws Exception {
            this.document = document;
            this.logoBytes = loadLogoBytes();
            this.topImageBytes = loadTopImageBytes();
            addPage();
        }

        void writeTitle(String title) throws Exception {
            if (!isFirstPage) {
                ensureSpace(40);
            } else {
                addTopImage();
                isFirstPage = false;
            }

            // Title styling
            ensureSpace(45);
            contentStream.beginText();
            contentStream.setFont(PDType1Font.HELVETICA_BOLD, 22);
            contentStream.newLineAtOffset(MARGIN, yPosition);
            contentStream.showText(toPdfText(title));
            contentStream.endText();
            yPosition -= 34;

            // Divider line under title
            drawLine(MARGIN, yPosition, PAGE_WIDTH - MARGIN, yPosition, 1.5f);
            yPosition -= 22;
        }

        void writeSectionHeading(String heading) throws Exception {
            ensureSpace(42);

            // Section heading
            contentStream.beginText();
            contentStream.setFont(PDType1Font.HELVETICA_BOLD, 14);
            contentStream.newLineAtOffset(MARGIN, yPosition);
            contentStream.showText(toPdfText(heading));
            contentStream.endText();
            yPosition -= SECTION_GAP + 10;
        }

        void writeField(String label, String value) throws Exception {
            List<String> lines = wrapText(toPdfText(value), (int) (VALUE_WIDTH / 5.6f));
            float requiredHeight = Math.max(1, lines.size()) * LINE_HEIGHT + FIELD_GAP;
            ensureSpace(requiredHeight + 8);

            float labelX = MARGIN;
            float valueX = labelX + LABEL_WIDTH + VALUE_GAP;
            float valueY = yPosition;

            // Label
            contentStream.beginText();
            contentStream.setFont(PDType1Font.HELVETICA_BOLD, FONT_SIZE);
            contentStream.newLineAtOffset(labelX, valueY);
            contentStream.showText(toPdfText(label) + ":");
            contentStream.endText();

            // Value
            for (String line : lines) {
                contentStream.beginText();
                contentStream.setFont(PDType1Font.HELVETICA, FONT_SIZE);
                contentStream.newLineAtOffset(valueX, valueY);
                contentStream.showText(line);
                contentStream.endText();
                valueY -= LINE_HEIGHT;
            }

            yPosition = valueY - FIELD_GAP;

            // Subtle separator line between fields
            drawLine(MARGIN, yPosition + 4, PAGE_WIDTH - MARGIN, yPosition + 4, 0.5f, 215, 215, 215);
            yPosition -= 6;
        }

        void close() throws Exception {
            if (contentStream != null) {
                contentStream.close();
                contentStream = null;
            }
            addFooterLogoOnlyOnLastPage();
        }

        private void drawLine(float x1, float y, float x2, float yEnd, float width) throws Exception {
            drawLine(x1, y, x2, yEnd, width, 100, 100, 100);
        }

        private void drawLine(float x1, float y, float x2, float yEnd, float width, int r, int g, int b) throws Exception {
            contentStream.setStrokingColor(r, g, b);
            contentStream.setLineWidth(width);
            contentStream.moveTo(x1, y);
            contentStream.lineTo(x2, yEnd);
            contentStream.stroke();
            contentStream.setStrokingColor(0, 0, 0);
        }

        private byte[] loadLogoBytes() throws Exception {
            ClassPathResource logoResource = new ClassPathResource("htc-logo.png");
            try (InputStream inputStream = logoResource.getInputStream()) {
                return inputStream.readAllBytes();
            }
        }

        private byte[] loadTopImageBytes() throws Exception {
            ClassPathResource imageResource = new ClassPathResource("vibethon.jpg");
            if (imageResource.exists()) {
                try (InputStream inputStream = imageResource.getInputStream()) {
                    return inputStream.readAllBytes();
                }
            }

            Path backendRelativePath = Path.of("../hackathon-frontend/src/assets/vibethon.jpg");
            if (Files.exists(backendRelativePath)) {
                return Files.readAllBytes(backendRelativePath);
            }

            Path rootRelativePath = Path.of("hackathon-frontend/src/assets/vibethon.jpg");
            if (Files.exists(rootRelativePath)) {
                return Files.readAllBytes(rootRelativePath);
            }

            return new byte[0];
        }

        private void addTopImage() throws Exception {
            if (topImageBytes == null || topImageBytes.length == 0) {
                return;
            }

            PDImageXObject topImage = PDImageXObject.createFromByteArray(document, topImageBytes, "vibethon-header");
            float scale = Math.min(TOP_IMAGE_MAX_WIDTH / topImage.getWidth(), TOP_IMAGE_MAX_HEIGHT / topImage.getHeight());
            float imageWidth = topImage.getWidth() * scale;
            float imageHeight = topImage.getHeight() * scale;
            PDRectangle mediaBox = page.getMediaBox();
            float x = (mediaBox.getWidth() - imageWidth) / 2;
            float y = mediaBox.getHeight() - MARGIN - imageHeight;

            contentStream.drawImage(topImage, x, y, imageWidth, imageHeight);
            yPosition = y - 30;
        }

        private void addPage() throws Exception {
            if (contentStream != null) {
                contentStream.close();
            }
            page = new PDPage(PDRectangle.A4);
            document.addPage(page);
            contentStream = new PDPageContentStream(document, page);
            yPosition = page.getMediaBox().getHeight() - TOP_MARGIN;
            isFirstPage = true;
        }

        private void ensureSpace(float requiredHeight) throws Exception {
            if (yPosition - requiredHeight < BOTTOM_MARGIN) {
                addPage();
            }
        }

        private void addFooterLogoOnlyOnLastPage() throws Exception {
            if (logoBytes == null || logoBytes.length == 0) {
                return;
            }

            PDImageXObject logo = PDImageXObject.createFromByteArray(document, logoBytes, "htc-logo-footer");
            float scale = Math.min(LOGO_MAX_WIDTH / logo.getWidth(), LOGO_MAX_HEIGHT / logo.getHeight());
            float logoWidth = logo.getWidth() * scale;
            float logoHeight = logo.getHeight() * scale;
            PDPage lastPage = document.getPage(document.getNumberOfPages() - 1);
            PDRectangle mediaBox = lastPage.getMediaBox();
            float x = (mediaBox.getWidth() - logoWidth) / 2;

            try (PDPageContentStream footerStream = new PDPageContentStream(
                document,
                lastPage,
                AppendMode.APPEND,
                true,
                true
            )) {
                footerStream.drawImage(logo, x, LOGO_BOTTOM_Y, logoWidth, logoHeight);
            }
        }

        private List<String> wrapText(String text, int maxLineLength) {
            List<String> lines = new ArrayList<>();
            if (text == null || text.isBlank()) {
                lines.add("");
                return lines;
            }

            for (String paragraph : text.split("\\R")) {
                StringBuilder line = new StringBuilder();
                for (String word : paragraph.split("\\s+")) {
                    if (line.length() + word.length() + 1 > maxLineLength && line.length() > 0) {
                        lines.add(line.toString());
                        line = new StringBuilder();
                    }
                    if (line.length() > 0) {
                        line.append(' ');
                    }
                    line.append(word);
                }
                if (line.length() > 0) {
                    lines.add(line.toString());
                }
            }
            return lines;
        }

        private String toPdfText(String text) {
            if (text == null) {
                return "";
            }

            return text
                .replace('\u2022', '-')
                .replace('\u2013', '-')
                .replace('\u2014', '-')
                .replace('\u2018', '\'')
                .replace('\u2019', '\'')
                .replace('\u201c', '"')
                .replace('\u201d', '"')
                .replaceAll("[^\\x09\\x0A\\x0D\\x20-\\x7E]", "");
        }
    }
}
